### ISSUE TITLE
Kaufkursberechnung falsch

### ISSUE THREAD

**Issue by skoehler-soocs** [EmDee/moneymoney-bondora#11]
Hallo,
seit neuestem ist die Kaufkursberechnung nicht mehr korrekt. 

Bei mir wird nur noch ein Bruchteil angezeigt und entsprechend stimmt der Depotwert nicht mehr. Die Abfrage via "https://www.bondora.com/de/dashboard/overviewnumbers/" zeigt aber die korrekten Werte (wie direkt auf der Bondora Website oder in der App an) bei ValueTooltip" an.

**Comment by EmDee** [comment]
> Hallo,
> seit neuestem ist die Kaufkursberechnung nicht mehr korrekt.
> 
> Bei mir wird nur noch ein Bruchteil angezeigt und entsprechend stimmt der Depotwert nicht mehr. Die Abfrage via "https://www.bondora.com/de/dashboard/overviewnumbers/" zeigt aber die korrekten Werte (wie direkt auf der Bondora Website oder in der App an) bei ValueTooltip" an.

Hallo! 
Danke für den Report. Das klingt allerdings komisch, wenn der ValueTooltip den korrekten Wert anzeigt. Ich versuche die Tage mal reinzuschauen.

**Comment by skoehler-soocs** [comment]
Seit heute funktioniert es wieder :-)

Keine Ahnung, ob das ein Bug bei dem Format von Bondora oder in MoneyMoney v 2.4.2 war.

**Comment by EmDee** [comment]
Super. Keine Arbeit für mich :)
