### ISSUE TITLE
account value displayed wrong in MoneyMoney(*100)

### ISSUE THREAD

**Issue by skdnp** [EmDee/moneymoney-bondora#12]
Hello.

My 97€ account value is displayed as 9.700€ in MoneyMoney. I wish microinvesting would yield such huge returns after one day, yet I suspect I should not spend this money yet :)
I tried different decimal/thousand separators, which are taking effect when displaying https://www.bondora.com/de/dashboard/overviewnumbers/ in the browser, but it doesn't solve the problem.
Any help would be appreciated. Screenshots for illustration.
Regards, 
skdnp

![Screen Shot 2021-05-11 at 17 27 12](https://user-images.githubusercontent.com/65280426/117843852-7b0d6c00-b27f-11eb-9177-2e1df8b26250.jpg)
![Screen Shot 2021-05-11 at 17 22 27](https://user-images.githubusercontent.com/65280426/117843858-7cd72f80-b27f-11eb-8b06-90a6fc859c17.jpg)

**Comment by EmDee** [comment]
Hi @skdnp,

maybe you got rich without knowing? I’ll try to have a look this weekend, can’t promise though.

**Comment by patbecks** [comment]
Hi @EmDee ,

Bondora gibt den Wert des Kontos mit 4 Stellen hinterm Komma aus. Bei mir ist der gleiche Faktor übertragen.

**Comment by EmDee** [comment]
Sorry this took so long, haven't had the time to check this out. Looks like Bondora is not returning the value in cents anymore, but Euro decimals. Will try to get a new version up today.
