### ISSUE TITLE
account value displayed wrong in MoneyMoney 

### ISSUE THREAD

**Issue by skdnp** [EmDee/moneymoney-bondora#16]
Installed latest version ... now browsing through yacht catalogues at the lounge of my local Lamborghini dealership :)
Displayed value in https://www.bondora.com/en/dashboard/overviewnumbers/ is €1412

![Screenshot 2022-01-13 at 18 47 48](https://user-images.githubusercontent.com/65280426/149383912-ab1b5f29-9448-41d6-9666-b8201f387dc1.png)

**Comment by EmDee** [comment]
I think you just got rich without noticing…

Have you checked your Bondora settings in regards to the mentioned limitations: https://github.com/EmDee/moneymoney-bondora#limitation

**Comment by skdnp** [comment]
hey, psst, you're in the market for a 2nd hand yacht yet? Had some Lambho-cravings lately?  I'm sure doing Bondora customer support for mere morons must rake in enough!

ofc settings were all over the place from trying to evade the last issue :) 
Thank's man und Frohes Neues!

**Comment by EmDee** [comment]
Hahaha. Glad that it helped! Just keep me in the back of your mind, in case you do end up with your yacht or Lambo in the surely very near future!

Cheers and frohes Neues!
