### ISSUE TITLE
Login per Google nicht möglich

### ISSUE THREAD

**Issue by mdohnke** [EmDee/moneymoney-bondora#18]
Der Login mit Google funktioniert mit dieser Extension nicht, oder?
<img width="262" alt="Bildschirmfoto 2022-12-02 um 13 44 48" src="https://user-images.githubusercontent.com/679141/205296761-80f94eeb-2a17-4973-acc2-5e27fad40cc2.png">

Ich habe dabei meine Google Adresse und mein Google Passwort eingegeben.

Protokoll im Anhang.
[bondora-extension-protocol.txt](https://github.com/EmDee/moneymoney-bondora/files/10141182/bondora-extension-protocol.txt)

**Comment by EmDee** [comment]
Nein, die extension funktioniert nur mit Email und Passwort.
