### ISSUE TITLE
Web scraping broken - Go&Grow Balance 0

### ISSUE THREAD

**Issue by MarcoH1986** [EmDee/moneymoney-bondora#19]
As of yesterday, Bondora seem to have changed their frontend, which breaks the web scraping of the plugin.

Just wanted to report it for now. Won't have the chance to look into it myself in the next couple of days. 

Thanks in advance for any effort. 

Version: 1.31

Regards
Marco

**Comment by EmDee** [comment]
@MarcoH1986 Thanks for the info. Unfortunately, I'm not using Bondora anymore and actually don't even have an account.

So I think the best is, if someone still using Bondora would take over this plugin. Maybe this person is you, @MarcoH1986? 🙂

I can write MoneyMoney to replace my extension on their website with the new repo, in case we have one.

**Comment by MarcoH1986** [comment]
@EmDee 

Ok, sounds fair. I will have a look at it in detail someday during the next week and will get back to you for a possible take over.

**Comment by TeeRiese** [comment]
@EmDee @MarcoH1986 I have also had the problem since 14.12.2023. The values via the following URL are 0.
https://www.bondora.com/en/dashboard/overviewnumbers/

I have written to the Bondora support team. But they only offer support for the interface.

**Comment by phaus** [comment]
The new URL seems to be https://www.bondora.com/api/GoGrowDashboard/GoGrowDashboardAccountInfo
I will have a look and try to update the plugin.

**Comment by phaus** [comment]
@EmDee  I did update and test receiving data from the new endpoint.
I guess the File Signature needs to be updated…

**Comment by EmDee** [comment]
Thanks to @phaus for the fix. Again, I can't test these changes anymore.

An unsigned extension can be found [here](https://github.com/EmDee/moneymoney-bondora/releases/download/1.4/Bondora-unsigned.lua)

In case you want to use the unsigned version, make sure to disable the verification of the signature in MoneyMoney, as described [here](https://moneymoney-app.com/api/webbanking/).

A signed version will be added as soon as MoneyMoney has signed it.

**Comment by TeeRiese** [comment]
I have also tested it. Works for me and I couldn't find any errors. I'll check again tomorrow to see if changes are applied correctly. The purchase price was still wrong. I had to change `name = "Account"` to another name once. After that, the purchase price was also displayed correctly. I was then able to change the name back to `Account`.

**Comment by EmDee** [comment]
It has been signed and is public on https://moneymoney-app.com/extensions/

I've also added the signed version to the release assets: https://github.com/EmDee/moneymoney-bondora/releases/tag/1.4

Thanks for all the help here, especially @phaus!

Again, if anyone feels like they want to own the extension, let me know.
