### ISSUE TITLE
Error refreshing balance

### ISSUE THREAD

**Issue by freakysheep** [EmDee/moneymoney-bondora#22]
Hi there, starting from today I get the error refreshing:

>  Bondora-3.lua:33: bad argument #1 to 'request' (string expected, got no value)

Did something from Bondoras side change?

**Comment by EmDee** [comment]
I assume it will be fixed by https://github.com/EmDee/moneymoney-bondora/pull/21

**Comment by EmDee** [comment]
Please test the latest release. Unsigned lua script attached: https://github.com/EmDee/moneymoney-bondora/releases/tag/1.5

Signed one will be added as soon as I've heard back from MoneyMoney.

**Comment by freakysheep** [comment]
Thank you, 1.5 works for me 👍

**Comment by EmDee** [comment]
Updated the release with the [signed version](https://github.com/EmDee/moneymoney-bondora/releases/download/1.5/Bondora.lua). Also updated on https://moneymoney-app.com/extensions/.
