### ISSUE TITLE
Bondora.lua:90: attempt to perform arithmetic on field 'total' (a nil value)

### ISSUE THREAD

**Issue by marothe** [EmDee/moneymoney-bondora#3]
The title says it. Getting this error when refreshing my accounts from the Bondora extension. 

"Bondora.lua:90: attempt to perform arithmetic on field 'total' (a nil value)"

Any ideas?

Moneymoney-Version: MoneyMoney Version 2.3.29 Retail

**Comment by EmDee** [comment]
Thanks for the report. I will see if I can get to it sometime this weekend.

Weird thing is: I’m not accessing any property named “total” nor is there a 90th line.

**Comment by marothe** [comment]
That is indeed strange. I re-downloaded the version from GitHub and now it works. Not sure where I got a different version from? But it works now. Sorry for that!

**Comment by andre68723** [comment]
same here, solved by chmod +x Bondora.lua . Whysoever, at least it works now.

-rw-r--r--@ 1 user  staff   3751  4 Okt 18:16 Bondora.lua
-rwxr-xr-x@ 1 user  staff   3751  4 Okt 18:16 Bondora.lua
