### ISSUE TITLE
Es werden zwei Positionen angezeigt, eine scheint die Zinsen abzuziehen

### ISSUE THREAD

**Issue by christo-ph** [EmDee/moneymoney-bondora#4]
Hi,

vielen Dank für das Plugin.

Ich habe ein Problem mit der Darstellung, und dadurch auch mit dem Gesamtbetrag. Eventuell benutze ich es auch falsch. Mir wurden heute Nacht Zinsen in Höhe von 0,09 gutgeschrieben, und gleichzeitig bei einer zweiten Position Account 0,09 abgezogen. Ist das bekannt?

<img width="911" alt="image" src="https://user-images.githubusercontent.com/16965068/91548443-aafd2500-e925-11ea-9464-d2672d8e5640.png">

**Comment by EmDee** [comment]
@christo-ph Sorry für die verspätete Antwort. Hat sich das Problem mittlerweile behoben? Ich kann das bei mir nicht reproduzieren.

**Comment by christo-ph** [comment]
Hi,

teils. Es ist so, dass bis zu einem vollen Euro Ertrag an Zinsen, die Cents dort im Account erst mal negativ sind.

Bin ich im oberen Beispiel irgendwann bei 501 EUR, so ist der Account wieder glatt gestellt. Bei 501,10 sind wieder 10 Cent im Account "minus".

Ich vermute das meldet Bondora irgendwie so zurück. Ist da auch nicht weiter schlimm.

Was ich noch gesehen habe, ist dass ich bei Einzahlungen manuell den "Kaufkurs" korrigieren muss. Er nimmt es sonst als "Gewinn" an.

Beispiel: Ich überweise 100 EUR, dann steht bei G&G Gewinn 20%, da er weiterhin von 500 EUR Kaufkurs ausgeht.

Danke!

**Comment by EmDee** [comment]
@christo-ph Mea culpa. Das Projekt ist bei mir leider etwas eingeschlafen, weil ich selbst nur noch sehr wenig Bondora nutze. Jetzt will ich die Weihnachtstage nutzen, um die ganzen Fehler zu beheben. Nutzt du die Extension noch, falls ja, hast du weiterhin die negative Darstellung?

Kannst du ggfs. den Output von https://www.bondora.com/de/dashboard/overviewnumbers/ zuschicken (Zahlen kannst du natürlich entsprechend schwärzen oder mir an support@martindinh.de zukommen lassen)?
