### ISSUE TITLE
Bondora.lua:90: attempt to perform arithmetic on field 'total' (a nil value)

### ISSUE THREAD

**Issue by nicoherpich** [EmDee/moneymoney-bondora#5]
Seit kurzem kommt beim Aktualisieren folgende Fehlermeldung:

Bondora.lua:90:` attempt to perform arithmetic on field 'total' (a nil value)

**Comment by EmDee** [comment]
@nicoherpich Das Problem wurde vor einiger Zeit gemeldet (https://github.com/EmDee/moneymoney-bondora/issues/3). Vielleicht helfen die Tipps in dem Issue weiter. Das Skript greift eigentlich nirgendwo auf ein `total` Feld zu.

**Comment by nicoherpich** [comment]
wow, neuer download hat das problem wirklich behoben. Danke!
