### ISSUE TITLE
Problem with balance fetching

### ISSUE THREAD

**Issue by christophbach** [EmDee/moneymoney-bondora#6]
Since several days Moneymoney is not able to retreive the current balance due to a script problem.

`Bondora.lua:90: attempt to perform arithmetic on field 'total' (a nil value) `

The response of the URLs looks valid to me, so I can't figure out, what's going on. Any ideas?

![Bildschirmfoto 2020-10-15 um 21 26 17](https://user-images.githubusercontent.com/487024/96176815-298d4080-0f2d-11eb-8b4b-c84a25cde098.png)

**Comment by EmDee** [comment]
@christophbach Looks like this is some recurring problem in the last days. The instruction in https://github.com/EmDee/moneymoney-bondora/issues/3 should help fix the issue. Basically re-downloading the extension.

**Comment by christophbach** [comment]
Woops, sorry for not checking the closed issues! It worked. Thanks mate!

**Comment by EmDee** [comment]
No worries! Glad it worked. Tbh, I have no idea what is heappening there and why a re-install is fixing the problem. It sounds a bit like `MoneyMoney` might be screwing with the extension files.

I guess I'll have to ask the next person that reports this to show me the lua file.
