### ISSUE TITLE
Total nil value Error

### ISSUE THREAD

**Issue by oyyyam** [EmDee/moneymoney-bondora#7]
Hi,
I just tried to set up my Bondora Account in MoneyMoney but I keep getting this Error:

<img width="665" alt="Bildschirmfoto 2020-10-22 um 12 19 57" src="https://user-images.githubusercontent.com/73284772/96860392-fc77eb00-1462-11eb-99e8-5fb2c2c5ee35.png">

**Comment by EmDee** [comment]
@oyyyam Please have a look at https://github.com/EmDee/moneymoney-bondora/issues/3

**Comment by EmDee** [comment]
@oyyyam Oh, but before you delete the `Bondora.lua` file, can you post the file here first please?

**Comment by oyyyam** [comment]
@EmDee It works now, but the total amount is slightly incorrect (0,59€ less). Old file enclosed

**Comment by EmDee** [comment]
Ok. I had a look at the `Bondora.lua` file and that one is completely different to the one I wrote. However, somehow that is the one that can be downloaded from the official website. It's weird, I will have to contact the `MoneyMoney` developer.
