### ISSUE TITLE
Bondora.lua:90: attempt to perform arithmetic on field 'total' (a nil value)

### ISSUE THREAD

**Issue by skoehler-soocs** [EmDee/moneymoney-bondora#8]
Beim Abruf meines Bondora Go & Grow Kontos tritt der Fehler "Bondora.lua:90: attempt to perform arithmetic on field 'total' (a nil value)" auf.

Der Abruf der Daten via URL sieht wie folgt aus...
---8<-----
{"ShowOverview":true,"Stats":[{"Title":"Wert des Kontos","Tooltip":"Der Wert des Kontos ist wie folgt berechnet: Verfügbares Guthaben + Vorgemerkte Investitionen + Ausstehendes Kapital - Überfälliges Kapital + Go \u0026 Grow","Value":"<BETRAG X> €","ValueTooltip":"<BETRAG X> €","SmallValue":null,"CustomButton":null,"SmallTooltip":null},{"Title":"Nettoertrag","Tooltip":"Der Nettogewinn wird folgendermaßen errechnet: Wert des Kontos - Einzahlungen + Auszahlungen - Bonus-Einkommen","Value":"<BETRAG X> €","ValueTooltip":"<BETRAG X> €","SmallValue":null,"CustomButton":null,"SmallTooltip":null},{"Title":"Brieftasche","Tooltip":"Verfügbarer Betrag zur Nutzung bei Bondora. Dieser Betrag ergibt sich aus der Differenz von Guthaben und vorgemerkten Investitionen.","Value":"<BETRAG X> €","ValueTooltip":"<BETRAG X> €","SmallValue":null,"CustomButton":null,"SmallTooltip":null}]}
---8<-----

Die echten Werte habe ich durch den Platzhalter "<BETRAG X>" ersetzt.

Leider kann ich den Code auf Grund der Signierung nicht selbst anpassen.

**Comment by EmDee** [comment]
HI @skoehler-soocs!

MoneyMoney hatte zwischendurch leider mal eine andere Bondora Extension verlinkt gehabt, die nichts mit dieser Implementierung zu tun hatte und den obigen Fehler auslöst.

Bitte nochmal auf der Extension Seite die "offizielle" (diese hier) herunterladen, dann sollte das gefixt sein.

Siehe https://github.com/EmDee/moneymoney-bondora/issues/3 und ähnliche.
