### ISSUE TITLE
Value vs. ValueTooltip

### ISSUE THREAD

**Issue by skoehler-soocs** [EmDee/moneymoney-bondora#9]
Nach der Neu-Installation des Plugins ( auf Grund von #8  ) werden die Nachkommastellen nicht korrekt angezeigt.

Bei der Berechnung werden anscheinend die Werte aus Value anstatt ValueTooltip herangezogen. Works as designed oder Bug? :) 

Danke.

**Comment by EmDee** [comment]
Als ich das damals umgesetzt habe, war es "works as designed". Ich versuche am WE mal reinzuschauen. Wenn `ValueTooltip` genauere Werte hat, dann nehme ich den; wobei der Name schon eher so klingt, als sollte es nicht den genaueren Wert haben.

**Comment by skoehler-soocs** [comment]
Super - Danke :)

Ich habe es mit meinem Bondora Konto abgeglichen und der ValueTooltip hat exakt die Werte wie auf der Bondora Website, d.h. den exakt korrekten Wert auf Nachkommastelle.

**Comment by EmDee** [comment]
Auch bei mir hat der `ValueTooltip`genauere Werte. Ich werde gleich eine neue Version zur Verfügung stellen. Eine signierte Version wird dann nachgereicht.

**Comment by EmDee** [comment]
-> https://github.com/EmDee/moneymoney-bondora/releases/tag/1.2
